//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D2Oracle.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("D2Oracle.Core.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config file created.
        /// </summary>
        public static string ConfigFileCreated {
            get {
                return ResourceManager.GetString("ConfigFileCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;D2Oracle&quot;
        ///{
        ///    &quot;uri&quot;           &quot;http://localhost:3000&quot;
        ///    &quot;timeout&quot;       &quot;5.0&quot;
        ///    &quot;buffer&quot;        &quot;0.5&quot;
        ///    &quot;throttle&quot;      &quot;0.5&quot;
        ///    &quot;heartbeat&quot;     &quot;30.0&quot;
        ///    &quot;data&quot;
        ///    {
        ///        &quot;provider&quot;      &quot;1&quot;
        ///        &quot;map&quot;           &quot;1&quot;
        ///        &quot;player&quot;        &quot;1&quot;
        ///        &quot;hero&quot;          &quot;1&quot;
        ///        &quot;abilities&quot;     &quot;1&quot;
        ///        &quot;items&quot;         &quot;1&quot;
        ///        &quot;buildings&quot;     &quot;1&quot;
        ///        &quot;draft&quot;         &quot;1&quot;
        ///        &quot;wearables&quot;     &quot;1&quot;
        ///        &quot;events&quot;        &quot;1&quot;
        ///    }
        ///}.
        /// </summary>
        public static string GsiFileContent {
            get {
                return ResourceManager.GetString("GsiFileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong folder.
        /// </summary>
        public static string IncorrectFolder {
            get {
                return ResourceManager.GetString("IncorrectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net worth.
        /// </summary>
        public static string NetWorth {
            get {
                return ResourceManager.GetString("NetWorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Dota 2 folder.
        /// </summary>
        public static string SelectDota2Folder {
            get {
                return ResourceManager.GetString("SelectDota2Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
    }
}
